# MySQL Database Configuration

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patika113hw4?characterEncoding=UTF8
    username: hbstudent
    password: hbstudent

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
